### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'download_method'

### ISSUE THREAD

**Issue by rsamf** [hynky1999/CmonCrawl#96]
Following the guide in the README, I use the extractor with the following command
```$ cmon extract config.json extracted_output html html_output/*.html```

and I get the following traceback:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/***/commoncrawl/.venv/lib/python3.10/site-packages/cmoncrawl/integrations/extract.py", line 219, in _extract_task
    download_method = DAOname(args.download_method) if args.download_method else None
AttributeError: 'Namespace' object has no attribute 'download_method'
"""

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/***/commoncrawl/.venv/bin/cmon", line 8, in <module>
    sys.exit(main())
  File "/***/.venv/lib/python3.10/site-packages/cmoncrawl/integrations/commands.py", line 59, in main
    args.func(args)
  File "/***/.venv/lib/python3.10/site-packages/cmoncrawl/integrations/extract.py", line 245, in run_extract
    pool.starmap(
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'Namespace' object has no attribute 'download_method'

```

**Comment by hynky1999** [comment]
Thanks for the report, should be fixed in the newest version
